version: '2'
services:
    docker-ssh-lamp:
        build: .
        hostname: docker-ssh-lamp
        image: docker-ssh-lamp
        links:
          - 'db:db'
          - 'db2:db2'
        volumes:
          - ./app:/app
          - ./var_log:/var/log
        ports:
          - "80:80"
          - "22:22"
        container_name: "docker-ssh-lamp"
        entrypoint: /app/docker_start.sh

    db:
      image: mariadb:5.5
      expose:
        - 3306
      environment:
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'pass'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'

    db2:
      image: mariadb:10.2.16
      expose:
        - 3307
      environment:
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'pass'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3307:3306'